version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  log_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: log/wattchecker-client.log
    maxBytes: 10000000
    backupCount: 10
    encoding: utf-8
loggers:
  __main__:
    level: DEBUG
    handlers: [console, log_file]
    propagate: no
  wattchecker:
    level: DEBUG
    handlers: [console, log_file]
    propagate: no
  data_handler:
    level: INFO
    handlers: [console, log_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
