version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  data:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  log_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: log/wattchecker-client.log
    maxBytes: 10000
    backupCount: 10
    encoding: utf-8
  data_csv:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: data
    filename: log/wattchecker-data.csv
    when: H
    backupCount: 0
    encoding: utf-8
  data_json:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: data
    filename: log/wattchecker-data.json
    when: H
    backupCount: 0
    encoding: utf-8
loggers:
  __main__:
    level: DEBUG
    handlers: [console, log_file]
    propagate: no
  wattchecker:
    level: DEBUG
    handlers: [console, log_file]
    propagate: no
  data_manager_csv:
    level: INFO
    handlers: [data_csv]
    propagate: no
  data_manager_json:
    level: INFO
    handlers: [data_json]
    propagate: no
root:
  level: DEBUG
  handlers: [console]